### ISSUE TITLE
Save cells output to file

### ISSUE THREAD

**Issue by egolep** [tamton-aquib/neorg-jupyter#1]
First of all: great plugin, I've been looking for something like this for Neorg for a long time.

I wonder if there is a way to actually save the output of the code cells to the `.norg` file or if it's a planned feature, as right now I get all the outputs to vanish when I close and reopen the file, even if I save

**Comment by egolep** [comment]
Ok my bad, I don't know why the `materialize` command wasn't showing with the others.
The question, then, is if I can call the `materialize` command on all cells at once instead of having to call it an a cell-by-cell basis

**Comment by tamton-aquib** [comment]
Heyyo @egolep,

Yep, glad you fond the materialize command, there are some more commands that arent documented right now like `materialize` and `hide`.But the plugin is currently limited and there is a list of todo to be done 😅 

Some of the main tasks are:
- Run all the blocks in order.
- Write back to ipynb.
- Better state management.

But as my time is limited, I might not be able to work for some time 😓

**Comment by tamton-aquib** [comment]
Hi @egolep,

I have been daily driving [molten-nvim](https://github.com/benlubas/molten-nvim) (+[otter.nvim](https://github.com/jmbuhr/otter.nvim/)) for jupyter notebook like experience inside neorg.

It has image support and all the above features I mentioned + lsp, formatting, etc.

Im closing this issue for now, but feel free to reopen just in case 👍🏻
